version: '3.8'

services:
  base:
    build:
      context: .
      dockerfile: base/Dockerfile
    image: base

  gateway:
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - insights
      - similarity

  insights:
    build:
      context: .
      dockerfile: job-insights/Dockerfile
      target: insights
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/insights_development
    depends_on:
      - db

  similarity:
    build:
      context: .
      dockerfile: similar-jobs/Dockerfile
      target: similarity
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/insights_development
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

volumes:
  pg_data:

